# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rservice.proto\"\x12\n\x03Uts\x12\x0b\n\x03uts\x18\x01 \x01(\t\"\x1e\n\x0b\x43ofirmation\x12\x0f\n\x07\x63onfirm\x18\x01 \x01(\x05\x32R\n\x0c\x43omunication\x12\x1f\n\x07\x41\x64\x64Uuts\x12\x04.Uts\x1a\x0c.Cofirmation\"\x00\x12!\n\tRemoveUts\x12\x04.Uts\x1a\x0c.Cofirmation\"\x00\x62\x06proto3'
)




_UTS = _descriptor.Descriptor(
  name='Uts',
  full_name='Uts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uts', full_name='Uts.uts', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=35,
)


_COFIRMATION = _descriptor.Descriptor(
  name='Cofirmation',
  full_name='Cofirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirm', full_name='Cofirmation.confirm', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['Uts'] = _UTS
DESCRIPTOR.message_types_by_name['Cofirmation'] = _COFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Uts = _reflection.GeneratedProtocolMessageType('Uts', (_message.Message,), {
  'DESCRIPTOR' : _UTS,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Uts)
  })
_sym_db.RegisterMessage(Uts)

Cofirmation = _reflection.GeneratedProtocolMessageType('Cofirmation', (_message.Message,), {
  'DESCRIPTOR' : _COFIRMATION,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Cofirmation)
  })
_sym_db.RegisterMessage(Cofirmation)



_COMUNICATION = _descriptor.ServiceDescriptor(
  name='Comunication',
  full_name='Comunication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUuts',
    full_name='Comunication.AddUuts',
    index=0,
    containing_service=None,
    input_type=_UTS,
    output_type=_COFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveUts',
    full_name='Comunication.RemoveUts',
    index=1,
    containing_service=None,
    input_type=_UTS,
    output_type=_COFIRMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMUNICATION)

DESCRIPTOR.services_by_name['Comunication'] = _COMUNICATION

# @@protoc_insertion_point(module_scope)
