# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class ComunicationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddUuts = channel.unary_unary(
        '/Comunication/AddUuts',
        request_serializer=service__pb2.Uts.SerializeToString,
        response_deserializer=service__pb2.Cofirmation.FromString,
        )
    self.RemoveUts = channel.unary_unary(
        '/Comunication/RemoveUts',
        request_serializer=service__pb2.Uts.SerializeToString,
        response_deserializer=service__pb2.Cofirmation.FromString,
        )


class ComunicationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddUuts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveUts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ComunicationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddUuts': grpc.unary_unary_rpc_method_handler(
          servicer.AddUuts,
          request_deserializer=service__pb2.Uts.FromString,
          response_serializer=service__pb2.Cofirmation.SerializeToString,
      ),
      'RemoveUts': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveUts,
          request_deserializer=service__pb2.Uts.FromString,
          response_serializer=service__pb2.Cofirmation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Comunication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
